print("Day 1 Printing Function")
print("The function is declered like this:")
print("print(\"what to print?\")")
print("Hello\"World")
print("Hello World \tHello World")
print("Hello World \nHello World")
print("Hello World \rHello World")
print("Hello World\bHello World")
print("Hello World\fHello World")
print("Hello World\\Hello World")
print("Hello World\'Hello World")
print("Hello World" + " _space_ " + "Hello World")